### ISSUE TITLE
ImportError: No module named regularizers

### ISSUE THREAD

**Issue by VictorLeeLk** [oswaldoludwig/Human-Action-Recognition-with-Keras#7]
Using Theano backend.
Traceback (most recent call last):
  File "HumanActionRecognition.py", line 18, in <module>
    from regularizers import EigenvalueRegularizer
ImportError: No module named regularizers

I have used the command ¨sudo pip install git+git://github.com/fchollet/keras.git --upgrade¨ to get the new keras,but still come up this problem?help!

**Comment by anjali-chadha** [comment]
Download EigenvalueDecay.py from [this repository](https://github.com/oswaldoludwig/Eigenvalue-Decay-Regularizer-for-Keras)

**Comment by poojab5** [comment]
File "HumanActionRecognition.py", line 18, in 
from regularizers import EigenvalueRegularizer
ImportError: No module named regularizers

EigenvalueDecay.py downloaded still issue persist...
help!
