### ISSUE TITLE
 Update your `Conv2D` call to the Keras 2 API

### ISSUE THREAD

**Issue by farshidrayhan** [oswaldoludwig/Human-Action-Recognition-with-Keras#9]
When i run the code i get the following warnings. Which leads to an error at the end.
```
Using TensorFlow backend.
/home/farshid/PycharmProjects/HumanActionRecognition/Main.py:67: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), name="conv1_1", activation="relu")`
  model.add(Convolution2D(64, 3, 3, activation='relu', name='conv1_1'))
/home/farshid/PycharmProjects/HumanActionRecognition/Main.py:69: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), name="conv1_2", activation="relu")`
  model.add(Convolution2D(64, 3, 3, activation='relu', name='conv1_2'))
/home/farshid/PycharmProjects/HumanActionRecognition/Main.py:73: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), name="conv2_1", activation="relu")`
  model.add(Convolution2D(128, 3, 3, activation='relu', name='conv2_1'))
/home/farshid/PycharmProjects/HumanActionRecognition/Main.py:75: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), name="conv2_2", activation="relu")`
  model.add(Convolution2D(128, 3, 3, activation='relu', name='conv2_2'))
Traceback (most recent call last):
  File "/home/farshid/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/farshid/anaconda3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/farshid/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 2 from 1 for 'max_pooling2d_2/MaxPool' (op: 'MaxPool') with input shapes: [?,1,112,128].

```

**Comment by zainulabidin302** [comment]
The error at the end is different than the warnings. you can downgrade your keras with `pip install keras==1.2.2` if you don't want to bother about `keras 2` much. Otherwise, you have to write keras 2 go through the release notes and check the fresh API.

The last error seems to be the error with dimensions of either input or output or some hidden layer.

**Comment by anjali-chadha** [comment]
[This](https://stackoverflow.com/questions/39815518/keras-maxpooling2d-layer-gives-valueerror) fixed the issue for me.

**Comment by txing001** [comment]
Hi,
I noticed that in python code row 36 the pre-trained model whole_model.h5 is used. I can't find it in your depository. Anyone ones where to find it? Thanks.
